// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDl1e7rcvw3Z2ppT9c3gKCi9mhuRwXK8_U',
    appId: '1:1008180737797:web:3d649dee63384f6e34696c',
    messagingSenderId: '1008180737797',
    projectId: 'msar-app-48df7',
    authDomain: 'msar-app-48df7.firebaseapp.com',
    storageBucket: 'msar-app-48df7.firebasestorage.app',
    measurementId: 'G-N18S8LBE3X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbbtVMuPdTWnO4Z95dpGuuKI_zMHCyiek',
    appId: '1:1008180737797:android:8dde2328f04a3da934696c',
    messagingSenderId: '1008180737797',
    projectId: 'msar-app-48df7',
    storageBucket: 'msar-app-48df7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALvjWi2IYZgxSmT8_b9qrtITKNfuHFPCg',
    appId: '1:1008180737797:ios:56d9755d01a3acc934696c',
    messagingSenderId: '1008180737797',
    projectId: 'msar-app-48df7',
    storageBucket: 'msar-app-48df7.firebasestorage.app',
    iosBundleId: 'com.example.msar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALvjWi2IYZgxSmT8_b9qrtITKNfuHFPCg',
    appId: '1:1008180737797:ios:56d9755d01a3acc934696c',
    messagingSenderId: '1008180737797',
    projectId: 'msar-app-48df7',
    storageBucket: 'msar-app-48df7.firebasestorage.app',
    iosBundleId: 'com.example.msar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDl1e7rcvw3Z2ppT9c3gKCi9mhuRwXK8_U',
    appId: '1:1008180737797:web:a4afb5290dd6e13b34696c',
    messagingSenderId: '1008180737797',
    projectId: 'msar-app-48df7',
    authDomain: 'msar-app-48df7.firebaseapp.com',
    storageBucket: 'msar-app-48df7.firebasestorage.app',
    measurementId: 'G-06SYWKD1CF',
  );
}
